version: "3.8"

services: 
  nginx:
    image: nginx:1.19.5-alpine
    container_name: mercuryo-client-nginx
    working_dir: /app
    volumes: 
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  
  php-fpm:
    build: ./docker/php-fpm
    container_name: mercuryo-client-php-fpm
    working_dir: /app
    volumes: 
      - ./app:/app
      - ./docker/php-fpm/custom.ini:/etc/php/7.4/fpm/conf.d/custom.ini

  mysql:
    image: mysql:8.0.22
    container_name: mercuryo-client-mysql
    working_dir: /app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_dev
      MYSQL_DATABASE: mercuryo_client_db
      MYSQL_USER: mercuryo_client_usr
      MYSQL_PASSWORD: mercuryo_client_pwd
    ports:
      - 8306:3306
    volumes: 
      - ./docker/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080